export const GET_API_PROJECT_AJAX_REQUEST = 'GET_API_PROJECT_AJAX_REQUEST'
export const GET_API_PROJECT_AJAX_SUCCESS = 'GET_API_PROJECT_AJAX_SUCCESS'
export const GET_API_PROJECT_AJAX_FAILED = 'GET_API_PROJECT_AJAX_FAILED'

export const GET_API_ROUTING_AJAX_REQUEST = 'GET_API_ROUTING_AJAX_REQUEST'
export const GET_API_ROUTING_AJAX_SUCCESS = 'GET_API_ROUTING_AJAX_SUCCESS'
export const GET_API_ROUTING_AJAX_FAILED = 'GET_API_ROUTING_AJAX_FAILED'
